services:
  backend:
    image: backend-image
    container_name: adisyonuygulamasi-backend
    build:
      context: ./src/backend
      dockerfile: BillApp.Api/Dockerfile
    ports:
      - "5025:5025"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5025
    depends_on:
      - db
    networks:
      - backend_network

  frontend:
    image: frontend-image
    container_name: adisyonuygulamasi-frontend
    build:
      context: ./src/frontend/BussinesApplication.Angular.Cli
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - backend_network

  db:
    image: postgres:15
    container_name: adisyonuygulamasi-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: MahalleOyunSalon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
